### ISSUE TITLE
Timing Rust examples in release mode

### ISSUE THREAD

**Issue by sanders41** [thedataquarry/rustinpieces#14]
Currently the Rust bench marks are taken in debug mode, ie:

```sh
cargo run -- 1000
```

Running in release mode will optimize the program to be faster and give a better idea of the numbers people would see in a released program.

```sh
cargo run -r -- 1000
```

**Comment by prrao87** [comment]
I'd done this for the `mock_data` generation piece, but forgot to do it for this one. Will make the updates to the docs too and close this once it's done 👍🏽

**Comment by prrao87** [comment]
Will be fixed by #17
