### ISSUE TITLE
Pool times out

### ISSUE THREAD

**Issue by prrao87** [thedataquarry/rustinpieces#16]
Relates to #6.

I'm trying to run the data loader to insert 1 million records, and it's giving me this error.

```console
Cannot insert data into persons table: PoolTimedOut
thread 'tokio-runtime-worker' panicked at rust/postgres_etl/src/bin/load_data.rs:56:6:
```

I tried changing the code to use `PgPoolOptions` like `main.rs` and I still get the same error. It works for a smaller number of records but the issue pops up when the number of records is 1 million.

**Comment by sanders41** [comment]
Does upping the available connections solve this issue? Something like `let pool = PgPoolOptions::new().min_connections(20).max_connections(20).connect(&pg_uri).await?;`. This way it wouldn't have to wait as long to get a connection.

If that doesn't were there are also some other options like `idle_timeout` that we could try setting to see if it makes a difference.

**Comment by prrao87** [comment]
I think the issue is in [this snippet](https://github.com/thedataquarry/rustinpieces/blob/433acba167e3faeb5ddd65bf2504f0e75ddb0e52/rust/postgres_etl/src/bin/load_data.rs#L79):

```rust
for person in persons.into_iter() {
    let task = tokio::spawn(insert(person, pool.clone()));
    tasks.push(task);
}
```

If there are a lot of records, for example 1 million persons, we're trying to clone the pool itself a million times. That doesn't seem reasonable surely? I'm looking at example code wherever I can find it to see how people are passing references to `PgPool` around

**Comment by sanders41** [comment]
I can't find any examples that don't use clone. One possibility I found is to use a semaphore to limit the number of concurrent requests. Something like this.

```rs
async fn insert(person: Person, pool: PgPool, permit: SemaphorePermit<'_>) {
    // Populate database
    sqlx::query!(
        r#"
            INSERT INTO persons (id, name, age, isMarried, city, state, country)
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            "#,
        person.id,
        &person.name,
        person.age,
        person.is_married,
        &person.city,
        &person.state,
        &person.country,
    )
    .execute(&pool)
    .await
    .expect("Cannot insert data into persons table");

    drop(permit);
}

async fn run() -> Result<usize, sqlx::Error> {
    dotenv().ok();
    // Get files
    let persons_csv_file = Path::new("data/persons.csv");

    let persons: Vec<Person> =
        read_data(persons_csv_file).expect("Did not obtain valid output from CSV");
    let counter = persons.len();
    println!("Number of persons: {}", counter);

    // Obtain connection
    let pg_uri = dotenvy::var("DATABASE_URL").unwrap();
    let pool = PgPoolOptions::new().min_connections(5).max_connections(5).connect(&pg_uri).await?;
    let semaphore = Arc::new(Semaphore::new(20));

    // Truncate table
    sqlx::query!("TRUNCATE TABLE persons")
        .execute(&pool)
        .await?;
    println!("Created persons table");
    // Insert data
    for person in persons.into_iter() {
        let pool_clone = pool.clone();
        let semaphore_clone = Arc::clone(&semaphore);
        tokio::spawn(async move {
            let permit = semaphore_clone.acquire().await.expect("Error acquiring semaphore");
            insert(person, pool_clone, permit).await;
        });
    }
    println!("Finished loading {:?} records", counter);
    Ok(counter)
}
```

I'm not sure what the best number of concurrent requests would be. 20 seemed reasonable, but there could be a better number

**Comment by prrao87** [comment]
Yup, I did some reading and I'm now clear that Arc has O(1) cloning and only clones pointers and doesn't allocate additional memory, so the size of the pool shouldn't matter.

I'll look into your example and let you know how that goes on my end, thanks!

**Comment by prrao87** [comment]
Although Arc has really efficient cloning, the approach we were following naively created clones for every record inserted. If we have 1M or 10M records of persons, it's not fair to expect zero impact by cloning the pool object that many times, even with Arc.

```rs
// Insert data
for person in persons.into_iter() {
   let task = tokio::spawn(insert(person, Arc::clone(&pool)));
   tasks.push(task);
}
```

In a realistic situation, we'd batch the dataset into sets of 50k-100k records (or similar) and iterate through the batches, so in those situations, creating that many clones at at time would be reasonable.

So I'm reformulating this example as 100K person records rather than a million records.
