### ISSUE TITLE
Use --all-targets when running clippy and clippy

### ISSUE THREAD

**Issue by sanders41** [thedataquarry/rustinpieces#24]
In updating the directory structure and running checks I noticed some places that have clippy warnings. These are all happening in the tests as far as I have seen so far.

The reason they are currently being missed is because `cargo clippy` and `cargo check` will skip running on tests. If we instead run `cargo clippy --all-targets` and `cargo check --all-targets` the checks will also be run on the tests.

**Comment by prrao87** [comment]
Shall we just add these commands to the Makefile to be able to call this via `make test` then?

**Comment by sanders41** [comment]
Yes, I think that makes sense. I considered doing it when updating the structure, but that PR was already so big I didn't want add more to it.
