### ISSUE TITLE
Add HashMap and HashSet to intro

### ISSUE THREAD

**Issue by prrao87** [thedataquarry/rustinpieces#27]
Two more data types that have roughly similar equivalents in Python/Rust can be added to the `intro` piece.

Python | Rust
--- | ---
`dict` | `HashMap`
`set` | `HashSet`

This is a good chance to highlight the differences too: things like how `HashMap` requires that the data types are homogenous, whereas `dict` allows key/value pairs of arbitrary types.

**Comment by prrao87** [comment]
@sanders41 I'm letting you take this one whenever you have the time. Also, I may have missed some common concepts/ideas that have common ground between Python/Rust, so feel free to add anything more as you see fit. The goal of the `intro` piece is to showcase rough counterparts in Python/Rust as much as possible, and the reader would come away with it thinking that Rust and Python have similar analogs (in many cases), and it's not infeasible to move between the languages.

**Comment by sanders41** [comment]
Sounds good, I'll work on some examples.
