### ISSUE TITLE
CI checks and pre-commit

### ISSUE THREAD

**Issue by sanders41** [thedataquarry/rustinpieces#29]
@prrao87  I'm thinking about adding pre-commit checks and also working on a way to have some CI checks to help us catch issues and make PR reviews easier. Do you have any objections to this?

**Comment by sanders41** [comment]
I finally got the rust CI working. Python as it turns out is going to be a bit more difficult. Because we aren't using modules with `__init__.py` files (and it makes sense that we aren't) pytest is unhappy about having multiple files with the same name. I'm trying to think of a solution for that still.

For mypy, ruff, etc to keep things simple and since we already have pre-commit working I suggest we use [pre-commit.ci](https://pre-commit.ci). I've been using it on my projects and like it. It is super fast, it frequently finishes before the github actions even start. Another nice thing about it is if it fails on something it can fix, a ruff format error for example, it automatically pushes an update to the PR to fix it. It's free for open source projects. If you like the idea you just need to go to the link and add the repo. I don't have access to do it since I don't own the repo.

**Comment by prrao87** [comment]
Done! I've used something similar to precommit-ci before, so that workflow makes sense. It's super annoying to have a CI fail for something as silly as `ruff format .`. I've added it to the repo, hope you can see it now.

**Comment by sanders41** [comment]
Looks, good. It works based off the pre-commit-config.yaml file so now it should start running on all new PRs.

I have some rough ideas on getting they python tests working, but I'm not sure if any of them are good yet. I should be able to test these ideas out locally so it should be easier to see if they work.

**Comment by prrao87** [comment]
This should be finished now, I think we can close this?

**Comment by sanders41** [comment]
I would like to get the Python tests running eventually, but I think it is fine to close this one.
