### ISSUE TITLE
Book doesn't deploy correctly with current setup

### ISSUE THREAD

**Issue by prrao87** [thedataquarry/rustinpieces#46]
I've tried following the example workflow from [the docs](https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions), and am having no luck deploying the book. It builds successfully, but I can't seem to get it to create a `gh-pages` branch that I can then point it to.

The goal is to have the book deployed on `thedataquarry.github.io/rustinpieces`, which will redirect to `rustinpieces.dev`. I think I have the structure set up correctly as per the [continuous integration](https://rust-lang.github.io/mdBook/continuous-integration.html) section of the docs, which states the following:

> If your book is not deployed at the root of the domain, then you should set the [output.html.site-url](https://rust-lang.github.io/mdBook/format/configuration/renderers.html#html-renderer-options) setting so that the 404 page works correctly. It needs to know where the book is deployed in order to load the static files (like CSS) correctly. For example, this guide is deployed at https://rust-lang.github.io/mdBook/, and the site-url setting is configured like this:

I've set it as this, which seems correct to me (the root domain is `thedataquarry.github.io`, and the `site-url` is `rustinpieces`, which matches the repo name just as `mdBook` does it).

```
# book.toml
[output.html]
site-url = "/rustinpieces/"
```

Open to other ideas or deployment methods!

**Comment by sanders41** [comment]
@prrao87 I made a change in the settings for gh-pages and the page is showing up now. I'll leave this open for you to check in case there was something else going on with the deploy that this change doesn't cover.

**Comment by prrao87** [comment]
Hi @sanders41, is the only change you made that you added a `CNAME` to the `gh-pages` branch? This was driving me crazy! I also made a change to the DNS settings on the domain at the same time as you (I removed the CNAME spec from there). So I'm not sure which change caused it to work! 

In any case, it works now! 🎉

**Comment by sanders41** [comment]
My update was to add the domain name the the custom domain in settings https://github.com/thedataquarry/rustinpieces/settings/pages. That may have autogenerated the `CNAME`? 

Could have been you DNS changes that got it also. Either way, glad its working now :tada:
