### ISSUE TITLE
Improve async performance for Postgres querying

### ISSUE THREAD

**Issue by prrao87** [thedataquarry/rustinpieces#6]
## To do

- [x] Insert a million records via `asyncpg` and `sqlx`, and study data loading performance in either approach.  
    - [x] Python script `load_data.py` successfully inserts a million records, this is fixed in #17 
    - [x] Rust `load_data.rs` is currently blocked by #16  
- [x] Run 10, 100 and 1000 async queries from `main.py` and `main.rs` and study the query throughput (QPS)
    - [x] Python script `main.py` runs 10, 100 and 1000 queries in 0.3s, 1s and 8.2 sec respectively (great performance!)
    - [x] Running the Rust script `main.rs` on the same dataset as the Python script was run on, the timings for 10, 100 and 1000 queries when run in release mode are similar: 0.3s, 1.1s and 8.3s. Nice!

**Comment by prrao87** [comment]
Hi @sanders41, I wanted to get your two cents on this one as I'm learning Rust (and I know you've been dabbling in it too). Would love to hear back from you when you have a moment!

## Goal

I have Python and Rust functions that are currently *defined* as async, but aren't running as async/non-blocking because in the end the queries are executed within a sync for loop. The performance is likely to vastly improve for 10, 100 and 1000 queries if correctly using a thread pool and managing connections to run them asynchronously.

### Python

This is the current form:

```python
async def perf_query(conn: Connection, age_limits: list[int]) -> int:
    for count, age_limit in enumerate(age_limits, 1):
        _ = await conn.fetchval(
            """
            SELECT COUNT(*) AS count
            FROM persons WHERE age > $1
            """,
            age_limit,
        )
    return count
```

I'm wondering on the best way to achieve non-blocking execution of these queries in a similar way to what I'd do in other DBs. I've tried queuing asyncio tasks for each query and then gathering them as I'd normally do, but asyncpg doesn't like that and errors out, because [it expects a connection pool](https://stackoverflow.com/a/66448094/1194761) to manage the stateful connections. 

### Rust

As one might imagine, doing this with a rudimentary knowledge of Rust is even harder. This is the current, simple form.

```rust
async fn perf_query(mut conn: PgConnection, ages: Vec<i16>) -> Result<i32, sqlx::Error> {
    let mut count = 0;
    for age in ages {
        let query = sqlx::query!(
            r#"
            SELECT COUNT(*) AS count
            FROM persons WHERE age > $1
            "#,
            age
        );
        _ = query.fetch_one(&mut conn).await?;
        count += 1;
    }
    Ok(count)
}
```

Because Rust isn't GIL-bound on threads like Python, the whole paradigm is different, and it looks like the best way to achieve non-blocking calls to the DB is to use tokio to spawn threads in a pool and move borrowed connections (a nice discussion on this is available [here](https://github.com/tokio-rs/tokio/discussions/4590)).

### Proposed steps

- [ ] Address Python and `asyncpg` pool to work with `asyncio`
- [ ] Address Rust and `sqlx` pool to work with `tokio` spawned threads (and handling the related ownership issues)

**Comment by sanders41** [comment]
I noticed this in the Python code and played around with it quickly. As you noticed already, running them concurrently results in and error from the connection being closed. Using a connection pool did fix this problem, but was slower since it needs to acquire a connection from the pool each time. While it is slower, it is honestly probably more realistic because in a "real world" application either a pool or new connections (which would be way slower) would be needed.

On the rust side tokio spawn sounds like a good idea here. I'm intrigued on this one, I'll play around with a bit and see if I come up with anything :smile:

**Comment by prrao87** [comment]
Agreed! I also noticed that the connection pool was slower, but as you pointed out, it's necessary to truly run things concurrently. I'll also tinker with both scripts and see where I go 😅

**Comment by prrao87** [comment]
To do:

- [ ] Insert a million records via `asyncg` and `sqlx`, and study data loading performance in either approach
- [ ] Run 10, 100 and 1000 async queries from `main.py` and `main.rs` and study the throughput in QPS

**Comment by prrao87** [comment]
@sanders41 I added you as a collaborator on this repo, that way we can both work of the clone of this repo and switch between our branches as needed 👍🏽

**Comment by sanders41** [comment]
Sounds good, I've accepted the invite
